### ISSUE TITLE
[New User] Nathan Greffe

### ISSUE THREAD

**Issue by NatGr** [montefiore-ai/alan-cluster#1]
**Are you a temporary user of the cluster?**
Yes, I was previously accessing the arya GPUs and would like to get access to this cluster for my master thesis.
*Until*: the 27th of june 2018

**Supervisor**
Professor Pierre Geurts

**Additional context**

**Comment by JoeriHermans** [comment]
Hi Nathan,

Your account has been added and will expire on the 1st of July 2019 (can be extended). An e-mail has been sent with account details.

Joeri
