### ISSUE TITLE
[Issue] Parse error in file /etc/slurm/slurm.conf line 118: " ThreadsPer"

### ISSUE THREAD

**Issue by CorentinJ** [montefiore-ai/alan-cluster#15]
**Describe the issue**
It seems that there is an issue with slurm, no commands work.

**To Reproduce**
Use any slurm command: squeue, sbatch, ...

**Comment by glouppe** [comment]
Oops. Joeri is adding more nodes. This will be fixed soon.

**Comment by glouppe** [comment]
It is now fixed. (Nodes are coming.)
