### ISSUE TITLE
[Feature Request] Automatic scratch allocation

### ISSUE THREAD

**Issue by JoeriHermans** [montefiore-ai/alan-cluster#17]
Configure Slurm such that scratch directories are automatically allocated, i.e., `$SCRATCH` points to `/scratch/job_id`. This directory should be automatically cleaned up when the job completes or crashes.

Let's have the related discussion here @CorentinJ @waliens. I'm currently encountering some issues with `slurmd`, but only minor things. Should have it up and running by Monday.

**Comment by JoeriHermans** [comment]
Hi all,

The scratch directory is currently configured. You can access it through `/scratch/$SLURM_JOB_ID`. At the moment I'm still looking how to export environment variables into the scope of the user-script. Nevertheless, you can start using the scratch using this trick.

Joeri

**Comment by waliens** [comment]
Thanks @JoeriHermans 
In my case, there is a large dataset (~130Go) that all my jobs are using. I could use the per-job scratch space but it means that each job would have a copy of the dataset which would take some time to set up and use a non-negligible amount of disk space. Would it be possible to replicate this dataset locally once on all nodes in some way ?

**Comment by JoeriHermans** [comment]
Hmmmmm. You are right, but I think this will give issues because you do not know a-priori where the job is going to be scheduled. Alternatively, I could do something like `/scratch/username/jobid` where you have read/write access to `/scratch/username` but that will result in nobody cleaning up their scratch partitions, i.e., I cannot think of a clean method across job.

However, you could do something like this: instead of running independent jobs, you can run your jobs using a task-array as this will be executed under the same job-id.

Maybe @glouppe has other ideas?

**Comment by CorentinJ** [comment]
Does the `/scratch/job_id` directory get cleaned up after the job? Otherwise you could force the execution on the same node with `sbatch <script> -w alan-compute-x`

**Comment by JoeriHermans** [comment]
Yes, `/scratch/job_id` does get cleaned up after the job is completed. You also have to view it from an administration point of view. In worst case, nobody will clean up their `/scratch` directories. So the disks will be full fairly quickly. But yes, you could force the script on a particular node, but that would defeat the purpose a bit of a GPU cluster imho.

**Comment by waliens** [comment]
I agree that selecting the node is not the way to go. 
Perhaps a solution would be to consider such replicated space for datasets only. We would replicate the folder currently in  `/data/datasets` on all nodes. This could be an issue if we have very large datasets or if a dataset should remain private from the other users of the cluster. Otherwise, as it is a read-only folder there is no problem with data piling up.

**Comment by waliens** [comment]
Another idea: you could indeed have a `/scratch/username` space allocated for all user that would be replicated on all nodes.  You would solve the problem of people not cleaning this folder by having a cron job doing the cleaning every week/day (?) if the user has no queued or running job. There would be no guarantee about the persistance of data stored in this folder in the long term ([CECI scratch system](http://www.ceci-hpc.be/scratch_space.html) made me think about this)

**Comment by JoeriHermans** [comment]
Ok, I'll do it like this (if this is ok for everyone):

1. Slurm Prolog (event hook before job start) will create the following if it does not exist.
   - `/scratch/$USERNAME`
   - `/scratch/$USERNAME/$SLURM_JOB_ID`
2. Slurm Epilog (event hook after job termination) will delete `/scratch/$USERNAME/$SLURM_JOB_ID`

This implies that `/scratch/$USERNAME` will not be deleted. So all the folders that a user made under `/scratch/$USERNAME` will remain. Every day, on midnight, a cronjob will wipe the scratch directories unless a job of that particular user is running on the compute node in question (pending jobs are ignored -> you don't know what node it will be scheduled to).

The following environment variables will be available in the user script:
- `$LOCALSCRATCH` points to `/scratch/$USERNAME`
- `$JOBSCRATCH` points to `/scratch/$USERNAME/$SLURM_JOB_ID`

**Comment by glouppe** [comment]
Sounds like a reasonable solution! We could maybe adjust the cleaning period from 1 day to 1 week? (I am not sure that many of us will use this, and those who do will know what they are doing.)

**Comment by CorentinJ** [comment]
I think this isn't so much of a good solution for big datasets unfortunately: I've copied 9gb in 2 hours and my datasets are all larger than 200gb. At this rate I'll be done copying in 2 days and then I've got to pray I didn't make any mistake in my script. I think that for this kind of situation you should let me keep my dataset permanently on the compute node and trust me make sure that I explicitly delete them. Considering my resource requirements aren't too high yet, I don't mind scheduling on a single node.

**Comment by JoeriHermans** [comment]
I've done some investigation into the issue at it seems that the RAID array at the central storage server are just maxed out (network bandwidth is OKish actually). This implies that the scratch partitioning I proposed earlier does not really help. @CorentinJ is experiencing these effects currently.

```
avg-cpu:  %user   %nice %system %iowait  %steal   %idle
           0.01    0.00    1.77   15.32    0.00   82.90

Device:         rrqm/s   wrqm/s     r/s     w/s    rMB/s    wMB/s avgrq-sz avgqu-sz   await r_await w_await  svctm  %util
sdb               0.20     0.00  448.60    2.00    56.28     0.01   255.86     9.16   20.26   20.36    0.00   2.22 100.00
sda               0.00     0.00    0.00    0.00     0.00     0.00     0.00     0.00    0.00    0.00    0.00   0.00   0.00
sdc               0.00     0.00    0.00    0.00     0.00     0.00     0.00     0.00    0.00    0.00    0.00   0.00   0.00
scd0              0.00     0.00    0.00    0.00     0.00     0.00     0.00     0.00    0.00    0.00    0.00   0.00   0.00
dm-0              0.00     0.00    0.00    0.00     0.00     0.00     0.00     0.00    0.00    0.00    0.00   0.00   0.00
dm-1              0.00     0.00    0.00    0.00     0.00     0.00     0.00     0.00    0.00    0.00    0.00   0.00   0.00
dm-2              0.00     0.00    0.00    0.00     0.00     0.00     0.00     0.00    0.00    0.00    0.00   0.00   0.00
```
I would suggest we create a spreadsheet of all the hardware in the cluster and reassign where needed. However, it depends on what kind of configuration we are going to take: a centralized NFS instance with an SSD RAID array to deal with the plenty read and writes, or install a filesystem like BeeGFS, Lustre, Ceph, ...

In any case, both approaches require us to reshuffle the hardware across the machines and install the cluster from scratch. That way we can have a RAID-0 localscratch of ~4TB on every machine. The installation isn't really an issue anymore since the configuration scripts are almost fully automated.

**Comment by JoeriHermans** [comment]
@CorentinJ 

> I think I will do the preprocessing of my future datasets strictly on compute nodes because it will likely take too much time on the master node. So the preprocessed datasets would already be there.

Just create another Slurm job with a task-array :) But yes, that would be a good idea.

**Comment by waliens** [comment]
@JoeriHermans Is the `/scratch/username` feature implemented ? Otherwise, would there be a temporary workaround for my 127Go dataset ? (my training is really hurt at this point, one epoch takes 40 minutes instead of 7).

**Comment by JoeriHermans** [comment]
Not yet, I'm busy with something at the moment. But I'll try to fix this ASAP, the change isn't that difficult. I noticed we have a network bottleneck at the moment, the switch is fully used at 125 MBps (because someone is writing a lot to the main disk instead of the scratch folder, I'm not sure but I think it is @AWehenkel, he's probably saving a lot of images :D).

I e-mailed SEGI to prepare an additional port on the switch to activate interface bonding https://wiki.debian.org/Bonding under a load-balancing mode. This should double the bandwidth to 250MBps. We are looking at other options as well (new 10Gbps switch or distributed file system).

**Comment by JoeriHermans** [comment]
@waliens 

Ok, I implemented the feature, however I didn't develop the "cleaning" script yet. The feature does the following at the moment:

1. When a job starts, it will create `/scratch/$USERNAME` and `/scratch/$USERNAME/$JOB_ID`.
2. When the job completes, it will delete `/scratch/$USERNAME/$JOB_ID`.

**Comment by CorentinJ** [comment]
Will this affect Loic's directory and mine?

**Comment by JoeriHermans** [comment]
@CorentinJ No, they will remain present as `/scratch/$USERNAME` will not be deleted. No reason to fret.

**Comment by JoeriHermans** [comment]
You know what would be a really hilarious, simple but temporary "fix". You just mount the NIC4 FS/scratch with `sshfs` or something (which is in the same network) :D

**Comment by CorentinJ** [comment]
@JoeriHermans if users with a permanent storage on the compute nodes are all on `alan-compute-01`, couldn't you make it so that all jobs prioritize the other nodes first, and would only select `alan-compute-01` if the resources are not available elsewhere?

**Comment by JoeriHermans** [comment]
That is not really fair from a queuing perspective :)

Also @CorentinJ , check you try a job on a different node to check if is faster now? Since @waliens runs from the Scratch partition as well, the disk saturation went from 99% to 0%. Maybe the issue is "solved" now. Might be because he is doing a lot of random read and writes, or opening and closing a lot of files.

Joeri

**Comment by CorentinJ** [comment]
Isn't it though? It makes virtually no difference to users who do not require the first cluster. When I said "prioritize the other nodes first", I meant that if both machines 01 and 02 can host a given job, it should be scheduled on 02. If only 01 can take it, then it will be scheduled on 01.

Also my issue is that I need storage local to the machine to run my job so I can only run it on 01 (or expect a ~12x slowdown)

**Comment by JoeriHermans** [comment]
> I meant that if both machines 01 and 02 can host a given job.
Given that > 2 GPU's are available AND if you explicitly state that you need machine 01, Slurm will assign 01 to you, and 02 to the other person. I'm pretty sure of this. However, typically only a single GPU becomes available at a time.

> Also my issue is that I need storage local to the machine to run my job so I can only run it on 01 (or expect a ~12x slowdown)

Which I think should not be an issue anymore as the disk saturation issue seems to be resolved.

**Comment by CorentinJ** [comment]
My point is that is there are several openings on multiple machines when someone wants to schedule a job, the job should be scheduled on any machine that has the resources other than 01. So that when someone who can only work on 01 comes later, there is a higher probability that there will be free slots in 01. But of course when the entire cluster is at 100% usage it won't make a difference.

> Also @CorentinJ , can you try a job on a different node to check if is faster now? Since @waliens runs from the Scratch partition as well, the disk saturation went from 99% to 0%:

I don't think I suffered much from this, it wasn't my issue.

> Which I think should not be an issue anymore as the disk saturation issue seems to be resolved.

If I understand correctly, scratch is local to every machine isn't it? I can try to run on the other nodes but that means I have to copy my datasets to the local `/scratch/` every time and that's still several hours of overhead. Plus I don't know about having hard copies on every compute node.

**Comment by JoeriHermans** [comment]
> My point is that if there are several openings on multiple machines when someone wants to schedule a job, the job should be scheduled on any machine that has the resources other than 01 if possible. So that when someone who can only work on 01 comes later, there is a higher probability that there will be free slots in 01.

Ok, I see now. I'm not going to do that though since the "advanced" administration options are not configured yet (else I could prioritize other nodes first). It will be when we will build v0.2 somewhere after the NeurIPS deadline.

> If I understand correctly, scratch is local to every machine isn't it? I can try to run on the other nodes but that means I have to copy my datasets to the local /scratch/ every time and that's still several hours of overhead. Plus I don't know about having hard copies on every compute node.

I think you are misunderstanding something. Try to run it from the centralized disk again (e.g., /home/cjemine/...), without using /scratch. Just as a test, as I think the saturation issue is resolved now, as described above.

**Comment by CorentinJ** [comment]
> Ok, I see now. I'm not going to do that though since the "advanced" administration options are not configured yet (else I could prioritize other nodes first). It will be when we will build v0.2 somewhere after the NeurIPS deadline.

Yeah no worry, it's more of a workaround anyway. I think that users who need permanent storage should try to get onto distinct machines. Unless the centralized storage is indeed faster; but I did just try it and it was as slow as it was before (~12x slowdown) when we discussed that Time Limits issue.

**Comment by JoeriHermans** [comment]
This absolutely makes no sense. All bandwidth is basically available, the main disks are not saturated at all. I increased the NFS daemons to like 128, and client threads to 32. You should not observe that behavior, although you do. :/ Anyway, I'm not going to bother, in a week or two we will have a distributed FS anyway.

**Comment by waliens** [comment]
> Maybe the issue is "solved" now. Might be because he is doing a lot of random read and writes, or opening and closing a lot of files.

Indeed solved for me, thanks for your help. Epoch duration went from 50 to 5 minutes 🙏 I was probably the cause of the issue, sorry for that ! Every sample of my (large) dataset is actually a file, so generating a random batch indeed yielded a lot of random reads (I don't write often though).
