### ISSUE TITLE
Rakesh Nath [raknath@gmail.com]

### ISSUE THREAD

**Issue by digirak** [montefiore-ai/alan-cluster#18]
**Are you a temporary user of the cluster?**
Deep Learning for Astrophysics PhD
*Until*: 2023

**Supervisor**
Olivier Absil

**Comment by JoeriHermans** [comment]
Hi @digirak 

Welcome, could you give me your full name (in the TODO field) and your e-mail address?

**Comment by digirak** [comment]
done

**Comment by JoeriHermans** [comment]
You should have received an e-mail with your use credentials.

Joeri

**Comment by digirak** [comment]
Yes indeed thank you!
