### ISSUE TITLE
[New User] ddefrere

### ISSUE THREAD

**Issue by ddefrere** [montefiore-ai/alan-cluster#19]
**Are you a temporary user of the cluster?**
Finding exoplanets in direct imaging data

*Until*: not defined.

**Supervisor**
O. Absil

**Additional context**
Part of the EPIC project to search and characterise exoplanet in direct imaging data

**Comment by JoeriHermans** [comment]
Hello and welcome!

Could I get your e-mail address?

**Comment by ddefrere** [comment]
Here is my e-mail address: ddefrere@uliege.be
Thanks!

Le lun. 13 mai 2019 à 19:13, Joeri Hermans <notifications@github.com> a
écrit :

**Comment by JoeriHermans** [comment]
An e-mail has been sent with your user-credentials. Have fun!
