### ISSUE TITLE
[New User] Robert Baudinet

### ISSUE THREAD

**Issue by robertbaudinet** [montefiore-ai/alan-cluster#20]
**Are you a temporary user of the cluster?**
No. I work with Pierre Barnabé for the GeMMe laboratory. We aim to classify scraps using multi-sensors images.

*Until*: not defined.

**Supervisor**
Eric Pirard
**Additional context**

**Comment by JoeriHermans** [comment]
Hi Robert,

Could I get your e-mail address?

**Comment by robertbaudinet** [comment]
Hi Joeri,
My main email address is baudinet.robert@gmail.com and, in case you need it, the one from the university is robert.baudinet@uliege.be.

**Comment by JoeriHermans** [comment]
Hi Robert, you should have an e-mail containing your user credentials. Have fun!
