### ISSUE TITLE
[New User] Christian Delacroix

### ISSUE THREAD

**Issue by ChrisDelaX** [montefiore-ai/alan-cluster#21]
I am Olivier Absil's postdoc. I will be working on High Contrast Imaging simulations.

**Comment by JoeriHermans** [comment]
Hello Christian,

Could I get your e-mail address?

**Comment by ChrisDelaX** [comment]
cdelacroix@uliege.be

**Comment by JoeriHermans** [comment]
An e-mail with your user credentials has been sent, have fun!
