### ISSUE TITLE
[New User] gorban

### ISSUE THREAD

**Issue by GillesOrban** [montefiore-ai/alan-cluster#22]
**Are you a temporary user of the cluster?**
Adaptive optics simulations, machine learning for wavefront sensing, high contrast imaging performances.
*Until*: not defined.

**Supervisor**
Olivier Absil

**Institutional email**
gorban@uliege.be

**Additional context**
Use of the cluster would be mostly within the framework of EPIC and METIS.

**Comment by JoeriHermans** [comment]
An e-mail has been sent with your user credentials, have fun!
