### ISSUE TITLE
[New User] Donovan Derkenne

### ISSUE THREAD

**Issue by delimz** [montefiore-ai/alan-cluster#23]
**Are you a temporary user of the cluster?**
Master thesis on histological image segmentation

*Until*: 20th august

**Supervisor**
Raphaël Marée

**Institutional email**
donovan.derkenne@student.uliege.be

**Additional context**
I  analyse big histological images(~25kp x 15kp, 19 images) by processing sequencial overlapping patches (1024x1024) with unet-like models . I have 17GB of pre-cropped patches, I developped with tensorflow 1.12, Training process is about 5 to 7 days per test on one 1080ti. I need 8 cpu and at least 20 GB of ram to preprocess and feed data to gpu optimally.

**Comment by JoeriHermans** [comment]
Hi Donovan,

I'll create your account shortly. Just a question, how large is the dataset and seperate images? Because at the moment we have some bandwidth / disk IO issues, so I might have to guide you a bit to do it optimally. Regarding the cluster, it is a Slurm based scheduler with a maximum training time of 7 days.

Joeri

**Comment by delimz** [comment]
the raw images are 5.6 G total , The crops are overlapped by half, that is why they take more space but the cropping of corresponding masks is time consuming so they are precomputed. the 49159 separate images take 16GB are between 0.1 and 0.6 MB plus 4 masks per images of less than 0.1 MB, I do batches of 5 images, an epoch is little less than one second,i see 3 to 6 MB/s from disk on average, I do image augmentation randomly on the fly which is what is taking processor time. I have a buffer of the augmented images but I reload the raw images each epoch, I can look into loading the raw images once. but I might need more ram

**Comment by JoeriHermans** [comment]
That is ok, most GPU nodes have 256GB of RAM, so you just request the amount you need.

**Comment by JoeriHermans** [comment]
I've added your account. You should have an e-mail with your user credentials.

Joeri
