### ISSUE TITLE
[New User] Pierre Barnabe

### ISSUE THREAD

**Issue by PierreBarnabe** [montefiore-ai/alan-cluster#26]
**Are you a temporary user of the cluster?**
Problem: building models for metallic scraps sorting (Project Reverse Metallurgy) on a multi-sensor prototype
*Until*: not defined.

**Supervisor**
Eric Pirard

**Institutional email**
pierre.barnabe@uliege.be

**Additional context**

**Comment by JoeriHermans** [comment]
Hi Pierre,

Sorry for the delay. You should have received an e-mail with your user credentials now.


Joeri
