### ISSUE TITLE
Training won't start when scheduled as a job

### ISSUE THREAD

**Issue by CorentinJ** [montefiore-ai/alan-cluster#28]
I have this tensorflow model that I can't manage to get training with slurm. It's the script `sv2tts/synthesizer_train.sh` in my home directory. If I ssh into the node that contains the dataset (alan-compute-02), I can run it directly and it works. But when run as a job, it freezes after initialization and outputs nothing more (I've let it run for 30 minutes). I lack the expertise to properly debug this, could I get a hand?

**Comment by JoeriHermans** [comment]
Can you start the job with Python in unbuffered mode?

```python
python -u script.py ...
```
This **should** flush everything to the log file immediately without the need to fill up the stdout/err buffers.

**Comment by CorentinJ** [comment]
Thank you Joeri, that was it. I had both the slurm output file and my logs not refreshing (I still haven't figured out the latter) so I had assumed something was wrong. The slurm output file now does get updated in real-time. It's something I could just have figured with `sattach` I think, but I've never managed to get that command working. The script on 01 is another job.
