### ISSUE TITLE
[New User] Arnaud Vallot

### ISSUE THREAD

**Issue by athanatos4** [montefiore-ai/alan-cluster#29]
**Are you a temporary user of the cluster?**
Master thesis: Active learning in industrial control.
Specifically, I need to perform some tests in order to finish the thesis.
*Until*: 8 June

**Supervisor**
Pierre Geurts

**Institutional email**
It is simply arnaud.vallot at student.uliege.be
Sorry for the peculiar format, I already had issues with bot crawlers on github, and I don't want to publicly display my e-mail.

**Comment by JoeriHermans** [comment]
Hi Arnaud,

Your account has been created. You should have received an e-mail with the user credentials.


Joeri
