### ISSUE TITLE
[New User] Corentin Jemine

### ISSUE THREAD

**Issue by CorentinJ** [montefiore-ai/alan-cluster#3]
**Are you a temporary user of the cluster?**
Yes. I need it for my thesis.
*Until*: the 8th of June. If I need an extension I will update this thread and mention you ASAP.

**Supervisor**
Prof. Gilles Louppe

**Additional context**
I am the student who needed his datasets transferred (VoxCeleb, LibriSpeech...). Note that I will require write access to these datasets.
If there is a possibility for getting access to multiple GPUs (even temporarily), please let me know.

**Comment by JoeriHermans** [comment]
Hi Corentin,

Could you check if you have received an with the account details now. You have access to the GPU cluster until the 1st of July.

It is possible to use mutiple GPUs, just add #SBATCH --gres=gpu:n where n is the number of GPU's you would like.

Joeri

**Comment by JoeriHermans** [comment]
Note that at the moment you can only request 4 GPU's that you can use in a data-parallel fashion. Next week we expect new nodes with 8 GPU's / machine.


Joeri

**Comment by CorentinJ** [comment]
Hello Joeri,

I did receive the account details, thanks. 

Some of my datasets have their owner set to Romain's account, since he helped copied them. These are the directories SV2TTS, Synthesizer, SynthesizerLibriTTS under my home directory. Do you think you could set me as the owner?

Also, are nvidia drivers installed? I couldn't find any nvidia command.

**Comment by glouppe** [comment]
Is this now solved? (It took some time to change the ownership of all those files)

**Comment by glouppe** [comment]
For the NVIDIA drivers, yes they are installed. But you dont see them from the master node (which has no GPU).

**Comment by CorentinJ** [comment]
Yes, I have the ownership back, thank you. 

Can we use the GPUs yet? I'm unfamiliar with the node system.

**Comment by glouppe** [comment]
The cluster is organized as a master node (alan-master) + compute nodes. Users submit jobs to the master, which then schedules and runs them on the compute nodes depending on the available resources. If the cluster is too busy, jobs are queued and then scheduled once resources become available. 

You need to prepare an environment that will be used within the script you send for execution. E.g., a conda environment.

Then you prepare a script `myscript.sh` such as:

```bash
#!/bin/bash
#SBATCH --gres=gpu:1
#SBATCH --cpus-per-task=1
#SBATCH --mem=2G
#SBATCH --time=12:00:00
source activate mypythonenv
python myscript.py args
``` 

The `SBATCH` flags specify the resources you ask to master. In this case, 1 GPU, 1 CPU, 2Gb of RAM and a total running time of up to 12 hours. The rest is a regular bash script in which you put everything you need. 

Once this is all prepared, on master you submit the job with the command `sbatch myscript.sh`. You can monitor the ongoing jobs using `squeue`.

**Comment by CorentinJ** [comment]
Thanks, I'll look into it. These are Slurm commands right? I can look up the documentation over there.

If you don't want to update the readme yet, I think you should make/keep an issue open with these infos because all other students are going to have the same questions.

**Comment by glouppe** [comment]
Any help is welcome to improve any part of the documentation :) 

Yes, those are slurm commands.
