### ISSUE TITLE
[New User] TODO

### ISSUE THREAD

**Issue by 15louisn** [montefiore-ai/alan-cluster#31]
**Are you a temporary user of the cluster?**
*Until*: October

**Supervisor**
Gilles Louppe

**Institutional email**
Louis.nelissen@student.uliege.be

**Additional context**
I am a student doing an internship under Prof. Louppe (in regards to the research of Matthia Sabatelli in Deep Reinforcement Learning Algorithms).

**Comment by JoeriHermans** [comment]
You should have received an e-mail with your user credentials.

Joeri
