### ISSUE TITLE
[New User] TODO

### ISSUE THREAD

**Issue by MaximeVandegar** [montefiore-ai/alan-cluster#32]
**Are you a temporary user of the cluster?**
I am doing my Master Thesis focused in deep learning. In that matter, I would like to use the cluster to train and test my algorithms. For now on, I am doing literature review and would like tu run some codes from papers for a better understanding.

*Until*: End June 2020

**Supervisor**
Pr. Gilles Louppe

**Institutional email**
Maxime.Vandegar@student.uliege.be

**Additional context**
/

**Comment by JoeriHermans** [comment]
You should have received an e-mail with your user credentials.
