### ISSUE TITLE
[New User] TODO

### ISSUE THREAD

**Issue by wphkoch** [montefiore-ai/alan-cluster#33]
**Are you a temporary user of the cluster?**
No
*Until*: not defined.

**Supervisor**
Eric Pirard
Godefroid Dislaire

**Institutional email**
ph.koch@uliege.be

**Additional context**
Classification and segmentation of rock materials based on multi-spectral/multi-sensors data. Possibly reinforcement learning later on. I work with Godefroid and Pierre Barnabe in GeMMe and just joined the group to support our ML and modelling efforts.
Thanks,
ph

**Comment by JoeriHermans** [comment]
You should have received an e-mail with your user credentials.
