### ISSUE TITLE
[New User] Pierre-Loup Nicolas

### ISSUE THREAD

**Issue by plnicolas** [montefiore-ai/alan-cluster#36]
Hello,
I would like to get access to the cluster in order to work on my master thesis (my main supervisor is Pierre Geurts), until September 2020.

**Supervisor**
Pierre Geurts and Raphaël Marée.

**Institutional email**
plnicolas@student.uliege.be

Best regards,
Pierre-Loup

**Comment by glouppe** [comment]
Your account has been created. I sent you credentials by email.
