### ISSUE TITLE
[New User] Michael Fonder

### ISSUE THREAD

**Issue by michael-fonder** [montefiore-ai/alan-cluster#37]
**Are you a temporary user of the cluster?**
Kind of... I need access to the cluster for the remaining time of my PhD thesis.
*Until*: End of PhD

**Supervisor**
Marc Van Droogenbroeck

**Institutional email**
michael.fonder@uliege.be

**Additional context**
/

**Comment by glouppe** [comment]
I created your account and sent your credentials by email. Enjoy!
