### ISSUE TITLE
[New User] Carles Cantero Mitjans

### ISSUE THREAD

**Issue by kanti92** [montefiore-ai/alan-cluster#39]
**Are you a temporary user of the cluster?**
I will be using the cluster for my PhD at the University of Liège

**Supervisor**
Marc Van Droogenbroeck

**Institutional email**
ccantero@uliege.be

**Additional context**

**Comment by JoeriHermans** [comment]
Could you add your full name in the TODO title? I'll add your account in the meantime.

**Comment by kanti92** [comment]
Yes, I've already received them.

Thanks :)

Cheers,
Carles
