### ISSUE TITLE
invalid user id

### ISSUE THREAD

**Issue by MalAstronomy** [montefiore-ai/alan-cluster#41]
**Describe the issue**
when i try to run 

#!/bin/bash
#SBATCH --job-name=test
#SBATCH --output=res.txt
#
#SBATCH --ntasks=1
#SBATCH --time=10:00
#SBATCH --mem-per-cpu=100

srun hostname
srun sleep 60

in my bash file as-  

sbatch submit.sh

but when i check in the result file, i see this error- 

srun: fatal: Invalid user id: 1046
srun: fatal: Invalid user id: 1046

Please help me understand what's going wrong.

**Comment by JoeriHermans** [comment]
I have some feeling what might be wrong, but could you try submitting the script without `srun`?

**Comment by MalAstronomy** [comment]
Okay, so when I ran the script without srun, the res.txt is empty (no invalid user id error) but i still dont see the job in the queue.

**Comment by JoeriHermans** [comment]
I'm taking over control of your account for a moment, give me a second.

**Comment by JoeriHermans** [comment]
Ping @MalAstronomy 

Edited the submission script. Works for me.


Joeri

**Comment by MalAstronomy** [comment]
Yes, now it works for me too, thanks. Although what was the issue?

**Comment by JoeriHermans** [comment]
@MalAstronomy An issue with `Munge`.  https://linux.die.net/man/7/munge

**Comment by Prakash2403** [comment]
@JoeriHermans Can you elaborate on what was the issue with `munge`? We are facing a similar issue on our HPC. Any help will be appreciated :)

Thanks in advance
