### ISSUE TITLE
[New User] Lorenzo König

### ISSUE THREAD

**Issue by LorenzoULG** [montefiore-ai/alan-cluster#42]
**Are you a temporary user of the cluster?**
I will perform FDTD simulations (optical propagation) on the Alan CPUs for my PhD project
*Until*: not defined.

**Supervisor**
Olivier Absil

**Institutional email**
lorenzo.konig@uliege.be

**Comment by glouppe** [comment]
Your account has been created. I sent your credentials by email. Sorry for the delay.
