### ISSUE TITLE
Invalid user id

### ISSUE THREAD

**Issue by LorenzoULG** [montefiore-ai/alan-cluster#43]
**Describe the issue**
When running a python script via mpiexec on the Alan CPUs an error "invalid user id: 1049" occurs. When I submit it without mpiexec it is generating the output as expected. 

**To Reproduce**
My submit.sh file:

`#!/bin/bash`
`#SBATCH --job-name=OPGtests`
`#SBATCH --output=optical_propagation_tests.txt`
`#SBATCH --ntasks=4`
`#SBATCH --time=59:00`
`#SBATCH --mem-per-cpu=100`
`mpiexec -n 4 python finite_HWP.py`

And the output file contains only:

`srun: fatal: Invalid user id: 1049`

Note that the job continues running but no further output is generated. 
I noticed that Malavika experienced the same error message a couple of months ago, although in a different context (Issue #41 )

**Additional Context**
I have a python environment activated to run Meep simulations (optical propagation) in parallel using mpirun / mpiexec. 
Please let me know if you need more detailed information. Thanks!

**Comment by JoeriHermans** [comment]
Might be that the provision script have not been executed when your account was added. I'll check this.

**Comment by JoeriHermans** [comment]
Hi @LorenzoULG 

Can you try again? I'll give your jobs priority to test this.

Joeri

**Comment by LorenzoULG** [comment]
It's running! Thanks a lot!

**Comment by JoeriHermans** [comment]
No problem, have fun.
