### ISSUE TITLE
[New User] Maxime Noirhomme

### ISSUE THREAD

**Issue by MaximeNoirhomme** [montefiore-ai/alan-cluster#5]
**Are you a temporary user of the cluster?**
I need acces for GPU for my master thesis
*Until*: end of June.

**Supervisor**
Pierre Geurts and Matthia Sabatelli

**Additional context**
None

**Comment by JoeriHermans** [comment]
Your account has been added and user credentials have been sent. Your account will be disabled on the 1st of July 2019.
