### ISSUE TITLE
[Feature Request] (Tiny) ImageNet

### ISSUE THREAD

**Issue by jm-begon** [montefiore-ai/alan-cluster#50]
I have copied TinyImageNet and imagenet datasets in my personal scratch folder (`/scratch/users/jmbegon/`). Since they are quite large, it might be of interest to move them to the general dataset scratch folder.

**Comment by JoeriHermans** [comment]
Thanks, I'm copying them over now. I'll close this issue whenever the transfer is complete.

**Comment by JoeriHermans** [comment]
Should be good to go now :) Closing this issue.
