### ISSUE TITLE
[Feature Request] Centralized TensorBoard storage

### ISSUE THREAD

**Issue by PierreBarnabe** [montefiore-ai/alan-cluster#51]
**Is your feature request related to a problem? Please describe.**
It is not really a problem, but I'm trying to make it easier to share with colleagues the progress of model training in tensorboard.
At the moment, I'm regularly starting tensorboard in my SSH connection and I access it locally (but only me) thanks to SSH tunneling.
I just found out about **tensorboard dev** which makes it really easy to share results online.
However, it seems very limited right now, and once you close the client, you have no way to launch it again later to update results on the same experiment. The only option at the moment seems to delete the previous experiment, create a new one (which takes a while), and share the new URL with colleagues.

**Describe the solution you'd like**
I was wondering if there was some way to execute "permanently" (i.e. without SSH connection) some program. 
More precisely, I was wondering if it was possible to run `tensorboard dev upload --logdir 'my_log_dir` in the background for days (for instance), and, at some point, to kill the execution when it is not needed anymore.
I'm of course assuming here that it doesn't use a lot of resources and that it wouldn't affect the performances of the cluster in any way.

**Additional context**
![tensorboard_dev](https://user-images.githubusercontent.com/6206121/108841752-8fbf5980-75d8-11eb-9b2a-78f69aea58fa.jpg)

**Comment by AWehenkel** [comment]
Hi Pierre, 
You may be interested by wandb (free for academics), it is a kind of improved tensorboard where data are stored on a server and accessible via a web interface.
Cheers,
Antoine

**Comment by PierreBarnabe** [comment]
Hi Antoine,
Thanks for the suggestion, it seems indeed to perfectly fit my needs. 
(I will use it in further jobs, but, after what I understand, I will still have to use tensorboard to visualize my previous runs)
Cheers,
Pierre
