### ISSUE TITLE
[Issue] TODO

### ISSUE THREAD

**Issue by stephdef08** [montefiore-ai/alan-cluster#52]
**Describe the issue**
Whenever I try to install a new package with anaconda or try to create an new environment, I get the following error:

CondaHTTPError: HTTP 000 CONNECTION FAILED for url <https://repo.anaconda.com/pkgs/main/linux-64/current_repodata.json>

**To Reproduce**
1. conda create --name env

**Expected behavior**
Anaconda should install the new package or create the new environment.

**Screenshots**

![Screenshot from 2021-07-17 13-05-17](https://user-images.githubusercontent.com/38205239/126034952-a0e1d386-ea45-482d-b09e-aa3a3720e138.png)

**Comment by stephdef08** [comment]
I have no idea why it was not working yesterday, but it is working today. Sorry for disturbing you.

**Comment by glouppe** [comment]
Thanks Stephane. It might have been due to the floods and its cascade of issues. For some time, I was without Internet myself. (I live close to the campus.)
