### ISSUE TITLE
cannot login to alan

### ISSUE THREAD

**Issue by MalAstronomy** [montefiore-ai/alan-cluster#59]
Hello (Joeri?), 

I cannot seem to login to alan anymore. When I type in my username and password in the alan/jupyterhub sign-in, it says "invalid username or password". 

Regards, 
Malavika

**Comment by JoeriHermans** [comment]
You have to check with Gilles. I do not have the necessary access (anymore) to connect remotely.

Cheers

**Comment by glouppe** [comment]
Fixed by resetting the password.
