### ISSUE TITLE
[Issue] `sacct` not displaying reserved/used resources

### ISSUE THREAD

**Issue by waliens** [montefiore-ai/alan-cluster#6]
**Describe the issue**
I usually use the slurm `sacct` command to monitor jobs (which are possibly not scheduled anymore, therefore not accessible via squeue). On alan, the command does not print anything regarding the resources used by the jobs (scheduled or not).

**To Reproduce**
An example command with the resulting (trimmed) output. For those jobs, I have requested 4 CPUs, 30Gb of RAM and 1 GPU. 

```log
$ sacct --format="JobID,AllocCPUS,AllocGRES,AveCPU,MinCPU,MinCPUNode,MinCPUTask,Ncpus,NTasks,UserCPU,TotalCPU,ReqMem,MaxVMSize,AveVMSize" --user rmormont
       JobID  AllocCPUS    AllocGRES     AveCPU     MinCPU MinCPUNode MinCPUTask      NCPUS   NTasks    UserCPU   TotalCPU     ReqMem  MaxVMSize  AveVMSize
------------ ---------- ------------ ---------- ---------- ---------- ---------- ---------- -------- ---------- ---------- ---------- ---------- ----------
1000146               0                                                                   0            00:00:00   00:00:00         0n
1000148               0                                                                   0            00:00:00   00:00:00         0n
1000149               0                                                                   0            00:00:00   00:00:00         0n
1000150               0                                                                   0            00:00:00   00:00:00         0n
1000151               0                                                                   0            00:00:00   00:00:00         0n
1000152               0                                                                   0            00:00:00   00:00:00         0n
1000153               0                                                                   0            00:00:00   00:00:00         0n
1000154               0                                                                   0            00:00:00   00:00:00         0n
1000155               0                                                                   0            00:00:00   00:00:00         0n
1000156               0                                                                   0            00:00:00   00:00:00         0n
1000157               0                                                                   0            00:00:00   00:00:00         0n
1000158               0                                                                   0            00:00:00   00:00:00         0n
1000159               0                                                                   0            00:00:00   00:00:00         0n
```

**Expected behavior**
The command should display the reserved/used resources (memory, cpu, gpu,...).

**Comment by JoeriHermans** [comment]
That's currently a problem with the way I handle the job accounting. In the ideal scenario we need to write the accounting_storage to a MySQL instance. Currently, I'm writing the job states to a file. So not all information is available. But since you are only interested in the `COMPLETED` or `FAILED` state, can't you just do `sacct -u jhermans JobID,State`?

**Comment by waliens** [comment]
Do you mean `sacct -u jhermans --format="JobID,State"` ? This command only show id and state of the job.  
I am actually interested to see resource usage after execution (whatever the state, it can also be `CANCELLED` btw). It is useful to adapt future jobs resources if have used too much or if a job was cancelled because I exceeded the reserved resources.

**Comment by JoeriHermans** [comment]
I have the configuration setup to enable this. But for this the cluster needs to be restarted (the master in particular). I will do this after the NeurIPS deadline.

**Comment by waliens** [comment]
Awesome, thanks !

**Comment by JoeriHermans** [comment]
Solved in next version.
