### ISSUE TITLE
[Issue] Cannot add dataset

### ISSUE THREAD

**Issue by jm-begon** [montefiore-ai/alan-cluster#7]
I wanted to place some dataset (actually, the one provided by PyTorch) on the cluster but the folder `/data/datasets/` is not writable.

So far I have placed my datasets in a local folder. As far as I'm concerned, this can stay like that, but I guess that if each user has its own copy of ImageNet, we will soon have memory issues.

**Comment by JoeriHermans** [comment]
Yes, only root currently has write permissions to said directory. But if you give me your local path I can move the dataset to the /data dir.

**Comment by JoeriHermans** [comment]
Ping @jm-begon

**Comment by jm-begon** [comment]
Ok thanks. Under `/home/jmbegon/data` are the dataset from `torchvision` that I am using.

Thanks Joeri :-)

**Comment by JoeriHermans** [comment]
Copying them now. You can delete them after your jobs are done.

@waliens do you have ImageNet somewhere? If not we'll have to download it.
